apiVersion: v1
kind: Namespace
metadata:
  name: videostreamingplatform
  labels:
    {{- include "vsp.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    {{- include "vsp.labels" . | nindent 4 }}
