apiVersion: v1
kind: Secret
metadata:
  name: rds-credentials
  namespace: videostreamingplatform
type: Opaque
stringData:
  host: {{ .Values.rdsCredentials.host }}
  username: {{ .Values.rdsCredentials.username }}
  password: {{ .Values.rdsCredentials.password }}
  database: {{ .Values.config.mysql.database }}
