apiVersion: v1
kind: Namespace
metadata:
  name: videostreamingplatform
  labels:
    name: videostreamingplatform

---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
