apiVersion: v1
kind: Namespace
metadata:
  name: videostreamingplatform
  labels:
    name: videostreamingplatform

---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    name: infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: analytics
  labels:
    name: analytics
