apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  namespace: videostreamingplatform
  labels:
    app: metadata-service
spec:
  type: NodePort
  selector:
    app: metadata-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: videostreamingplatform
  labels:
    app: data-service
spec:
  type: NodePort
  selector:
    app: data-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
      protocol: TCP
