apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  namespace: videostreamingplatform
  labels:
    app: metadata-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: metadata-service
  ports:
    - name: http2
      port: 8080
      targetPort: 8080
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: videostreamingplatform
  labels:
    app: data-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: data-service
  ports:
    - name: http2
      port: 8081
      targetPort: 8081
      protocol: TCP
