environment = "dev"
aws_region  = "us-east-1"

vpc_cidr                 = "10.0.0.0/16"
public_subnet_cidrs      = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs     = ["10.0.11.0/24", "10.0.12.0/24"]
kubernetes_version       = "1.30"
node_group_min_size      = 10
node_group_max_size      = 20
node_group_desired_size  = 10
node_instance_types      = ["t3.micro"]
rds_instance_class       = "db.t3.micro"
s3_video_retention_days  = 30
opensearch_instance_type  = "t3.small.search"
opensearch_instance_count = 1
opensearch_volume_size    = 10
cloudfront_price_class    = "PriceClass_100"
cloudfront_default_ttl    = 3600
cloudfront_max_ttl        = 86400
redis_node_type           = "cache.t3.micro"
