// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Simplified version for testing and development

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// DataServiceClient is the client API for DataService service
type DataServiceClient interface {
	InitiateUpload(ctx context.Context, in *UploadInitiateRequest, opts ...grpc.CallOption) (*UploadInitiateResponse, error)
	UploadChunk(ctx context.Context, in *UploadChunkRequest, opts ...grpc.CallOption) (*UploadChunkResponse, error)
	GetUploadProgress(ctx context.Context, in *UploadProgressRequest, opts ...grpc.CallOption) (*UploadProgressResponse, error)
	CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error)
	ListUploads(ctx context.Context, in *ListUploadsRequest, opts ...grpc.CallOption) (*ListUploadsResponse, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) InitiateUpload(ctx context.Context, in *UploadInitiateRequest, opts ...grpc.CallOption) (*UploadInitiateResponse, error) {
	out := new(UploadInitiateResponse)
	err := c.cc.Invoke(ctx, "/dataservice.DataService/InitiateUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) UploadChunk(ctx context.Context, in *UploadChunkRequest, opts ...grpc.CallOption) (*UploadChunkResponse, error) {
	out := new(UploadChunkResponse)
	err := c.cc.Invoke(ctx, "/dataservice.DataService/UploadChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetUploadProgress(ctx context.Context, in *UploadProgressRequest, opts ...grpc.CallOption) (*UploadProgressResponse, error) {
	out := new(UploadProgressResponse)
	err := c.cc.Invoke(ctx, "/dataservice.DataService/GetUploadProgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error) {
	out := new(CompleteUploadResponse)
	err := c.cc.Invoke(ctx, "/dataservice.DataService/CompleteUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) ListUploads(ctx context.Context, in *ListUploadsRequest, opts ...grpc.CallOption) (*ListUploadsResponse, error) {
	out := new(ListUploadsResponse)
	err := c.cc.Invoke(ctx, "/dataservice.DataService/ListUploads", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service
type DataServiceServer interface {
	InitiateUpload(context.Context, *UploadInitiateRequest) (*UploadInitiateResponse, error)
	UploadChunk(context.Context, *UploadChunkRequest) (*UploadChunkResponse, error)
	GetUploadProgress(context.Context, *UploadProgressRequest) (*UploadProgressResponse, error)
	CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadResponse, error)
	ListUploads(context.Context, *ListUploadsRequest) (*ListUploadsResponse, error)
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded
type UnimplementedDataServiceServer struct {
}

func (UnimplementedDataServiceServer) InitiateUpload(context.Context, *UploadInitiateRequest) (*UploadInitiateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateUpload not implemented")
}

func (UnimplementedDataServiceServer) UploadChunk(context.Context, *UploadChunkRequest) (*UploadChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadChunk not implemented")
}

func (UnimplementedDataServiceServer) GetUploadProgress(context.Context, *UploadProgressRequest) (*UploadProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadProgress not implemented")
}

func (UnimplementedDataServiceServer) CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteUpload not implemented")
}

func (UnimplementedDataServiceServer) ListUploads(context.Context, *ListUploadsRequest) (*ListUploadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUploads not implemented")
}

func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}

type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_InitiateUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadInitiateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).InitiateUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataservice.DataService/InitiateUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).InitiateUpload(ctx, req.(*UploadInitiateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_UploadChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).UploadChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataservice.DataService/UploadChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).UploadChunk(ctx, req.(*UploadChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetUploadProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetUploadProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataservice.DataService/GetUploadProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetUploadProgress(ctx, req.(*UploadProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_CompleteUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).CompleteUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataservice.DataService/CompleteUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).CompleteUpload(ctx, req.(*CompleteUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_ListUploads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUploadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).ListUploads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataservice.DataService/ListUploads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).ListUploads(ctx, req.(*ListUploadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dataservice.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateUpload",
			Handler:    _DataService_InitiateUpload_Handler,
		},
		{
			MethodName: "UploadChunk",
			Handler:    _DataService_UploadChunk_Handler,
		},
		{
			MethodName: "GetUploadProgress",
			Handler:    _DataService_GetUploadProgress_Handler,
		},
		{
			MethodName: "CompleteUpload",
			Handler:    _DataService_CompleteUpload_Handler,
		},
		{
			MethodName: "ListUploads",
			Handler:    _DataService_ListUploads_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dataservice.proto",
}
