// Code generated by protoc-gen-go. DO NOT EDIT.
// Simplified version for testing and development

package pb

// Upload represents an upload session
type Upload struct {
	Id               string  `json:"id,omitempty"`
	VideoId          string  `json:"video_id,omitempty"`
	UserId           string  `json:"user_id,omitempty"`
	TotalSize        int64   `json:"total_size,omitempty"`
	UploadedSize     int64   `json:"uploaded_size,omitempty"`
	UploadedChunks   int32   `json:"uploaded_chunks,omitempty"`
	TotalChunks      int32   `json:"total_chunks,omitempty"`
	Status           string  `json:"status,omitempty"`
	Percentage       float64 `json:"percentage,omitempty"`
	SpeedMbps        float64 `json:"speed_mbps,omitempty"`
	EstimatedSeconds int64   `json:"estimated_seconds,omitempty"`
	CreatedAt        string  `json:"created_at,omitempty"`
	UpdatedAt        string  `json:"updated_at,omitempty"`
	CompletedAt      string  `json:"completed_at,omitempty"`
}

// UploadInitiateRequest message
type UploadInitiateRequest struct {
	VideoId   string `json:"video_id,omitempty"`
	UserId    string `json:"user_id,omitempty"`
	TotalSize int64  `json:"total_size,omitempty"`
}

// UploadInitiateResponse message
type UploadInitiateResponse struct {
	UploadId  string `json:"upload_id,omitempty"`
	ChunkSize int64  `json:"chunk_size,omitempty"`
	Message   string `json:"message,omitempty"`
}

// UploadChunkRequest message
type UploadChunkRequest struct {
	UploadId    string `json:"upload_id,omitempty"`
	ChunkIndex  int32  `json:"chunk_index,omitempty"`
	TotalChunks int32  `json:"total_chunks,omitempty"`
	Checksum    string `json:"checksum,omitempty"`
	ChunkData   []byte `json:"chunk_data,omitempty"`
}

// UploadChunkResponse message
type UploadChunkResponse struct {
	UploadId   string `json:"upload_id,omitempty"`
	ChunkIndex int32  `json:"chunk_index,omitempty"`
	Success    bool   `json:"success,omitempty"`
	Message    string `json:"message,omitempty"`
}

// UploadProgressRequest message
type UploadProgressRequest struct {
	UploadId string `json:"upload_id,omitempty"`
}

// UploadProgressResponse message
type UploadProgressResponse struct {
	UploadId         string  `json:"upload_id,omitempty"`
	Percentage       float64 `json:"percentage,omitempty"`
	UploadedBytes    int64   `json:"uploaded_bytes,omitempty"`
	TotalBytes       int64   `json:"total_bytes,omitempty"`
	UploadedChunks   int32   `json:"uploaded_chunks,omitempty"`
	TotalChunks      int32   `json:"total_chunks,omitempty"`
	SpeedMbps        float64 `json:"speed_mbps,omitempty"`
	EstimatedSeconds int64   `json:"estimated_seconds,omitempty"`
}

// CompleteUploadRequest message
type CompleteUploadRequest struct {
	UploadId      string `json:"upload_id,omitempty"`
	FinalChecksum string `json:"final_checksum,omitempty"`
}

// CompleteUploadResponse message
type CompleteUploadResponse struct {
	UploadId string `json:"upload_id,omitempty"`
	Status   string `json:"status,omitempty"`
	Message  string `json:"message,omitempty"`
}

// ListUploadsRequest message
type ListUploadsRequest struct {
	UserId string `json:"user_id,omitempty"`
}

// ListUploadsResponse message
type ListUploadsResponse struct {
	Uploads []*Upload `json:"uploads,omitempty"`
}
