global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'metadata-service'
    static_configs:
      - targets: ['metadataservice:8080']

  - job_name: 'data-service'
    static_configs:
      - targets: ['dataservice:8081']
